### ISSUE TITLE
macOS JPG save hangs infinitely

### ISSUE THREAD

**Issue by hyperknot** [imazen/imageflow#578] opened 2021-02-27 11:47 UTC
Same command, the jpg one hangs.

```
imageflow_tool v1/querystring --in 1.png --out out.png --command "format=png"
imageflow_tool v1/querystring --in 1.png --out out.jpg --command "format=jpg"
```

From: https://github.com/imazen/imageflow/releases/download/v1.5.5-rc59/imageflow-v1.5.5-rc59-d384d92d-osx-x86_64.tar.gz, but same for 1.5.4 as well.

**Comment by lilith** [comment] 2021-02-28 03:01
Is this an Apple Silicon device (M1)?

**Comment by hyperknot** [comment] 2021-02-28 03:16
No, Late 2013 Macbook Pro 15.

**Comment by lilith** [comment] 2021-03-12 05:51
Are you sure it hangs indefinitely or just runs a really long time? If not it could be a duplicate of https://github.com/imazen/imageflow/issues/576

**Comment by hyperknot** [comment] 2021-03-12 17:11
The image was very small, PNG conversion was < 1 sec. I terminated the JPG conversion after like 1 minute. So I don't know if it's really really slow or it'll be there indefinitely.
Saving the same image with mozjpeg's cjpeg is also < 1 sec.

**Comment by lilith** [comment] 2021-03-13 19:59
Please try v1.5.6-rc60. If the issue persists, please reopen! Thank you!

**Closed by lilith** 2021-03-13 19:59 UTC
