### ISSUE TITLE
Transparent png show black background

### ISSUE THREAD

**Issue by robertomatute** [imazen/imageflow#158] opened 2017-10-23 13:39 UTC
Hi,

Thanks for your amazing software, it works really well!!

We are having a weird problem with these images:
## Original
![imo-1-original](https://user-images.githubusercontent.com/614413/31891458-188e5fb4-b7cc-11e7-8c65-57c745070e59.png)

(by the way, its the same image of #153, different problem)

I optimized the original image using [Tinypng](https://tinypng.com):

## Optimized
![imo-1-optimized](https://user-images.githubusercontent.com/614413/31891594-7ae85034-b7cc-11e7-8893-682dffa275e9.png)

In both cases the image has a transparent background.  

Everything look fine if you see the image directly.  

But when asked through imageflow appears with a different background:

## Served by imageflow

![imo-1-optimized-imageflow](https://user-images.githubusercontent.com/614413/31891803-0cf3dd36-b7cd-11e7-834a-205c218a6612.png)

In the optimization the image size decrease 75%, which is great for our home page.  

It is something about the Tinypng optimization?  or perhaps is a profile mishandling in imageflow?

Thanks for all your help!!

**Comment by RossLieberman** [comment] 2017-10-23 17:23
I can verify this as happening for me as well. What I found was the cause was a transparent PNG in using the LibJpeg instead of LibPng. I tried to find a way to matte on a white background before resizing, but the options are limited in the .NET version (at this time) I didn't see any easy way to do it. The workaround for me was to determine the mime-type by it's extension and use the different libraries.

My Code in C#:
```c#
using (var fileStream = File.Open($"{diskPath}{imageName}", FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
{
    using (var b = new FluentBuildJob())
    {
        var r = await b
                .Decode(fileStream, false)
                .ConstrainWithin((uint?)resizeParams.Width, (uint?)resizeParams.Height)
                .EncodeToBytes(GetCurrentFormat(extension))
                .FinishAsync();

        var bytes = r.First.TryGetBytes();

        if (bytes != null)
            using (var stream = new MemoryStream(bytes.Value.Array, bytes.Value.Offset, bytes.Value.Count))
            {
                httpContext.Response.ContentType = GetContentType(extension);   							
                await stream.CopyToAsync(httpContext.Response.Body);
            }
    }
```

```c#
private IEncoderPreset GetCurrentFormat(string extension)
{
    switch (extension)
    {
        case ".png":
            return new LibPngEncoder();
    }
    
    return new LibJpegTurboEncoder();
}
```

**Comment by robertomatute** [comment] 2017-10-27 14:59
Ross, thanks for your response.

Sorry, is not clear to me what could be the solution.  Do you plan to address this issue? or is better to address in the future?

Temporary I can use the non-optimized image, but it would be nice save those extra bits.

Thanks, again!

**Comment by RossLieberman** [comment] 2017-10-27 16:10
I'm not certain I can help you with the workaround, but I can try to assist. I'm not an image optimization guy, just using the solution and encountered the same thing. Could you provide the code, command, or JSON you are using to optimize the image? And I can see if there is any parallel to how I changed things to work.

**Comment by robertomatute** [comment] 2017-10-27 16:39
Ross, I am using Imageflow server (not library), so I dont think is possible for me to use your workaround.

Appreciate your help!!

**Comment by nathanaeljones** [comment] 2017-10-27 16:54
Can you add &format=png to the URL?

**Comment by robertomatute** [comment] 2017-10-27 17:29
Adding `format=png` doesnt change the result:

![format=png](https://leon-rojo.imolko.net/img/slider/imo-2.png?format=png)

By the way, this is the address of the stage enviroment for imageflow:
https://leon-rojo.imolko.net/img/slider/imo-2.png

**Comment by RaulGuichard** [comment] 2018-09-25 23:41
For me it seems to happen when the file is an 8bit-PNG, works for 24 and 32 bits PNGs'. Did anyone find a solution or does anyone know what part in the code we could modify to add 8 bit PNG detection as well?

**Comment by sridhard** [comment] 2019-03-01 06:32
Hi,

Any update on this issue?

**Comment by sridhard** [comment] 2019-03-06 04:12
Hi @lilith any update on this issue?

**Comment by sridhard** [comment] 2019-03-08 06:43
@robertomatute have you resolved this issue?
@lilith is there any plans to solve this or this repo is dead?

**Comment by lilith** [comment] 2019-03-08 07:09
Is this happening in the current release? I thought we had landed an upstream fix. Perhaps not.

I've not been very active lately due to health issues, but I can put up a $500 bounty on this bug until I can work on it. 

And I will soon (in weeks) be actively looking for a developer to help get Imageflow production-ready.

**Comment by sridhard** [comment] 2019-03-08 08:24
Hi lilith,

We are using imageflow version 1.1.0-rc18 (d32265746* 2018-11-02). It is happening in this version. 1.1.0-rc18 is the latest version I can find. Image flow is very nice and the outputs has better quality and compression rate compared to other tools. But due to small bugs it is not yet production ready.

Takecare of your health.

**Comment by lilith** [comment] 2020-04-12 10:59
I've reproduced this in master on the demo server. 
Local url: http://localhost:39876/demo_images/private/png_transparent_background_black_bug.png?width=50

**Closed** 2020-04-24 20:21 UTC
Labels: priority-high

**Comment by lilith** [comment] 2020-04-24 20:23
Sorry for taking so long on this. As of today I have a linux machine than can actually do debugging, so future fixes should land much faster.
